### ISSUE TITLE
Modifications to Inherited Role/ClusterRole not reflected

### ISSUE THREAD

**Issue by sabre1041** [redhat-cop/dynamic-rbac-operator#3]
If a modification to a Role/ClusterRole is made, the change is not reflected in the following areas:

1. Cache should be updated whenever a change to Roles/ClusterRoles occur
2. DynamicRole/DynamicClusterRole should reflect the updated inherited policy

## Scenario

1. Create a custom `ClusterRole` with rights to Services, ConfigMaps and Secrets
2. Create `DynamicClusterRole` that inherits the above and removes access to `Secrets`
3. Edit custom `ClusterRole` and remove `ConfigMaps`
4. `DynamicClusterRole` still provides access to `ConfigMaps`

**Comment by jacobsee** [comment]
+1 on the second bullet, this needs to be implemented and just doesn't exist yet. For the first - inherited roles and clusterroles are not cached at all. The only things that are cached right now is a list of the CRDs in the cluster, and a compiled list of all _possible_ cluster policies (basically a fully enumerated `cluster-admin`). This compiled list is updated every time a CRD is modified in a way that would affect it. Inherited roles and clusterroles are fetched every time a new ruleset is computed though, so, this project just needs to add watches on role and clusterrole resources to account for changes to inherited resources.
